<?php

/**
 * @file
 * Contains sempra_bio.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\prev_next\PrevNextHelperInterface;

/**
 * Implements hook_help().
 */
function sempra_bio_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sempra_bio module.
    case 'help.page.sempra_bio':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to create the prev nexv buttons for the Bio profiles.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sempra_bio_theme() {
  return [
    'sempra_bio' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * Get prev and next bio profile.
 */
function sempra_bio_get_node($nid, $op){
  $node_item_id = prev_next_nid($nid, 'prev');
}

